import type {
  EatCleanCategory,
  EatCleanMeal,
  EatCleanOrder,
  EatCleanOrderQuote,
  EatCleanStorefront,
} from './types'

export const EAT_CLEAN_CATEGORIES: EatCleanCategory[] = [
  { id: 'all', label: 'Tất cả' },
  { id: 'balanced', label: 'Cân bằng' },
  { id: 'high-protein', label: 'Giàu đạm' },
  { id: 'low-carb', label: 'Ít tinh bột' },
  { id: 'vegetarian', label: 'Thuần thực vật' },
  { id: 'breakfast', label: 'Bữa sáng' },
  { id: 'lunch', label: 'Bữa trưa' },
  { id: 'dinner', label: 'Bữa tối' },
  { id: 'snack', label: 'Bữa phụ' },
  { id: 'combo', label: 'Combo ngày' },
]

export const DEMO_EAT_CLEAN_MEALS: EatCleanMeal[] = [
  {
    id: 'ec-chicken-brown-rice',
    slug: 'uc-ga-gao-lut',
    name: 'Ức gà áp chảo & gạo lứt',
    shortDescription: 'Đạm nạc, carb chậm và rau củ theo mùa.',
    description: 'Ức gà ướp thảo mộc áp chảo, ăn cùng gạo lứt dẻo và rau củ hấp. Một phần no vừa, phù hợp cho ngày tập luyện.',
    imageUrl: '/images/eat-clean/chicken-pepper.webp',
    category: 'balanced',
    tags: ['Bán chạy', 'Không chiên ngập dầu'],
    price: 79000,
    compareAtPrice: 89000,
    currency: 'VND',
    nutrition: { calories: 486, protein: 43, carbs: 52, fat: 12, fiber: 7 },
    portionLabel: '420 g · 1 phần',
    ingredients: ['Ức gà', 'Gạo lứt', 'Bông cải xanh', 'Cà rốt', 'Dầu ô-liu', 'Thảo mộc'],
    allergens: [],
    prepMinutes: 18,
    rating: 4.9,
    reviewCount: 128,
    badge: 'Aura chọn',
    available: true,
  },
  {
    id: 'ec-salmon-pumpkin',
    slug: 'ca-hoi-bi-do',
    name: 'Cá hồi nướng & bí đỏ',
    shortDescription: 'Omega-3, rau xanh và sốt chanh ít béo.',
    description: 'Cá hồi nướng vừa chín cùng bí đỏ, đậu que và salad lá. Sốt chanh được đóng riêng để bạn chủ động lượng dùng.',
    imageUrl: '/images/eat-clean/salmon-vegetables.webp',
    category: 'low-carb',
    tags: ['Omega-3', 'Low carb'],
    price: 109000,
    currency: 'VND',
    nutrition: { calories: 438, protein: 36, carbs: 29, fat: 20, fiber: 8 },
    portionLabel: '390 g · 1 phần',
    ingredients: ['Cá hồi', 'Bí đỏ', 'Đậu que', 'Xà lách', 'Chanh vàng'],
    allergens: ['Cá'],
    prepMinutes: 20,
    rating: 4.8,
    reviewCount: 86,
    badge: 'Low carb',
    available: true,
  },
  {
    id: 'ec-beef-quinoa',
    slug: 'bo-hat-diêm-mach',
    name: 'Bò tiêu đen & diêm mạch',
    shortDescription: 'Bữa giàu đạm cho ngày vận động cường độ cao.',
    description: 'Thăn bò xào nhanh với tiêu đen, dùng cùng diêm mạch, nấm và rau cải. Công thức kiểm soát dầu và độ mặn.',
    imageUrl: '/images/eat-clean/beef-egg-salad.webp',
    category: 'high-protein',
    tags: ['45 g protein', 'Sau tập'],
    price: 99000,
    currency: 'VND',
    nutrition: { calories: 522, protein: 45, carbs: 46, fat: 18, fiber: 6 },
    portionLabel: '430 g · 1 phần',
    ingredients: ['Thăn bò', 'Diêm mạch', 'Nấm', 'Cải thìa', 'Tiêu đen'],
    allergens: ['Đậu nành'],
    prepMinutes: 18,
    rating: 4.9,
    reviewCount: 104,
    badge: 'Giàu đạm',
    available: true,
  },
  {
    id: 'ec-tofu-soba',
    slug: 'dau-hu-soba',
    name: 'Đậu hũ nướng & mì soba',
    shortDescription: 'Đạm thực vật, nhiều màu rau và vị mè rang.',
    description: 'Đậu hũ nướng giòn cạnh, mì soba và rau củ trộn sốt mè rang nhẹ. Phù hợp cho một bữa chay đủ chất.',
    imageUrl: '/images/eat-clean/hero-bowl.webp',
    category: 'vegetarian',
    tags: ['Ăn chay', 'Nhiều chất xơ'],
    price: 72000,
    currency: 'VND',
    nutrition: { calories: 455, protein: 24, carbs: 58, fat: 16, fiber: 11 },
    portionLabel: '410 g · 1 phần',
    ingredients: ['Đậu hũ', 'Mì soba', 'Bắp cải tím', 'Edamame', 'Mè rang'],
    allergens: ['Đậu nành', 'Mè', 'Gluten'],
    prepMinutes: 16,
    rating: 4.7,
    reviewCount: 63,
    badge: 'Plant power',
    available: true,
  },
  {
    id: 'ec-yogurt-oats',
    slug: 'yogurt-yen-mach',
    name: 'Yogurt Hy Lạp & yến mạch',
    shortDescription: 'Bữa sáng mát nhẹ, giàu protein và chất xơ.',
    description: 'Yogurt Hy Lạp không đường, yến mạch ngâm, trái cây theo mùa và hạt rang đóng riêng để giữ độ giòn.',
    imageUrl: '/images/eat-clean/hero-bowl.webp',
    category: 'breakfast',
    tags: ['Bữa sáng', 'Không đường tinh luyện'],
    price: 59000,
    currency: 'VND',
    nutrition: { calories: 362, protein: 25, carbs: 45, fat: 10, fiber: 8 },
    portionLabel: '330 g · 1 phần',
    ingredients: ['Yogurt Hy Lạp', 'Yến mạch', 'Dâu', 'Chuối', 'Hạnh nhân'],
    allergens: ['Sữa', 'Hạt cây'],
    prepMinutes: 5,
    rating: 4.8,
    reviewCount: 75,
    badge: 'Sáng nhanh',
    available: true,
  },
  {
    id: 'ec-shrimp-noodle',
    slug: 'tom-bun-gao-lut',
    name: 'Tôm nướng & bún gạo lứt',
    shortDescription: 'Tươi nhẹ, đủ năng lượng và ít chất béo bão hòa.',
    description: 'Tôm nướng tỏi, bún gạo lứt, rau thơm và rau củ giòn. Nước trộn chua ngọt giảm đường được đóng riêng.',
    imageUrl: '/images/eat-clean/salmon-vegetables.webp',
    category: 'balanced',
    tags: ['Tươi nhẹ', 'Sốt riêng'],
    price: 89000,
    currency: 'VND',
    nutrition: { calories: 448, protein: 34, carbs: 56, fat: 10, fiber: 7 },
    portionLabel: '400 g · 1 phần',
    ingredients: ['Tôm', 'Bún gạo lứt', 'Dưa leo', 'Cà rốt', 'Rau thơm'],
    allergens: ['Giáp xác'],
    prepMinutes: 15,
    rating: 4.7,
    reviewCount: 59,
    available: false,
  },
]

export const DEMO_EAT_CLEAN_STOREFRONT: EatCleanStorefront = {
  source: 'demo',
  deliveryMode: 'scheduled',
  serviceDate: new Date(Date.now() + 86_400_000).toISOString().slice(0, 10),
  asapEnabled: true,
  meals: DEMO_EAT_CLEAN_MEALS,
  categories: EAT_CLEAN_CATEGORIES,
  featuredMealIds: ['ec-chicken-brown-rice', 'ec-salmon-pumpkin', 'ec-beef-quinoa'],
  orderingEnabled: true,
  nextDeliveryLabel: 'Giao sớm nhất: ngày mai · 07:00–09:00',
  freeDeliveryThreshold: 250000,
  deliverySlots: [
    { id: 'morning', label: '07:00–09:00', active: true },
    { id: 'lunch', label: '10:30–12:30', active: true },
    { id: 'evening', label: '16:30–18:30', active: true },
  ],
  districts: [
    { id: 'hai-chau', name: 'Hải Châu', active: true },
    { id: 'thanh-khe', name: 'Thanh Khê', active: true },
    { id: 'son-tra', name: 'Sơn Trà', active: true },
    { id: 'ngu-hanh-son', name: 'Ngũ Hành Sơn', active: true },
    { id: 'cam-le', name: 'Cẩm Lệ', active: true },
    { id: 'lien-chieu', name: 'Liên Chiểu', active: true },
  ],
  notice: 'Đang hiển thị thực đơn mẫu để bạn khám phá giao diện Eat Clean.',
  orders: [],
}

export function createDemoQuote(items: Array<{ mealId: string; quantity: number }>): EatCleanOrderQuote {
  const lines = items.flatMap((item) => {
    const meal = DEMO_EAT_CLEAN_MEALS.find((candidate) => candidate.id === item.mealId)
    if (!meal || !meal.available) return []
    return [{ ...item, name: meal.name, unitPrice: meal.price, lineTotal: meal.price * item.quantity }]
  })
  const subtotal = lines.reduce((total, line) => total + line.lineTotal, 0)
  const deliveryFee = subtotal >= 250000 ? 0 : 20000
  const estimatedArrivalAt = new Date(Date.now() + 45 * 60 * 1000).toISOString()
  return {
    quoteId: `demo-quote-${Date.now()}`,
    lines,
    subtotal,
    deliveryFee,
    discount: 0,
    total: subtotal + deliveryFee,
    currency: 'VND',
    distanceMeters: 3400,
    routeDurationSeconds: 900,
    estimatedArrivalAt,
    promisedAt: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    deliveryFeeBeforeDiscount: 20000,
    deliveryFeeDiscount: subtotal >= 250000 ? 20000 : 0,
    feeRuleVersion: 'demo-distance-v1',
    serviceAreaLabel: 'Nội thành Đà Nẵng',
    unavailableMealIds: items.filter((item) => !lines.some((line) => line.mealId === item.mealId)).map((item) => item.mealId),
  }
}

export function createDemoOrder(
  quote: EatCleanOrderQuote,
  input: Omit<EatCleanOrder, 'id' | 'code' | 'status' | 'items' | 'subtotal' | 'deliveryFee' | 'discount' | 'total' | 'currency' | 'createdAt'>,
): EatCleanOrder {
  const suffix = String(Date.now()).slice(-6)
  const createdAt = new Date().toISOString()
  return {
    ...input,
    id: `demo-order-${suffix}`,
    code: `EC${suffix}`,
    status: 'confirmed',
    items: quote.lines,
    subtotal: quote.subtotal,
    deliveryFee: quote.deliveryFee,
    discount: quote.discount,
    total: quote.total,
    currency: quote.currency,
    createdAt,
    updatedAt: createdAt,
    canCancel: true,
  }
}
