import { test, expect } from '@playwright/test'
for (const width of [360, 390, 430]) {
  test(`production workspace manual confirm and continuation at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/tests/schedule-ui/index.html')
    await expect(page.getByRole('heading', { name: 'Xếp lịch PT' })).toBeVisible()
    await page.locator('.schedule-cell').filter({ hasText: 'Lan' }).focus()
    await page.keyboard.press('Enter')
    await page.getByRole('button', { name: 'Chọn Ngọc', exact: true }).click()
    expect(await page.evaluate(() => (window as any).__scheduleCalls.filter((x: any) => x.operation === 'command').length)).toBe(0)
    await page.getByRole('button', { name: 'Xác nhận xếp ca', exact: true }).click()
    await expect(page.locator('.schedule-assigned-row').filter({ hasText: 'Ngọc' })).toBeVisible()
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Tối ưu tiếp', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Chọn chi nhánh' })).toBeDisabled()
    await expect(page.getByRole('combobox', { name: 'Chọn chi nhánh' })).toBeEnabled()
    const modes = await page.evaluate(() => (window as any).__scheduleCalls.filter((x: any) => x.operation === 'generate').map((x: any) => x.input.mode))
    expect(modes).toEqual(['continue'])
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  })
}
test('failed move leaves inspector and original session intact; retry succeeds', async ({ page }) => {
  await page.goto('/tests/schedule-ui/index.html')
  await page.locator('.schedule-cell').filter({ hasText: 'Lan' }).focus()
    await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Chuyển ca của Lan', exact: true }).click()
  await page.getByRole('combobox', { name: 'Ca đích', exact: true }).selectOption('T3-6')
  await page.evaluate(() => { (window as any).__failScheduleCommand = true })
  await page.getByRole('button', { name: 'Xác nhận chuyển ca', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('ca cũ được giữ')
  await expect(page.locator('.schedule-assigned-row').filter({ hasText: 'Lan' })).toBeVisible()
  await page.evaluate(() => { (window as any).__failScheduleCommand = false })
  await page.getByRole('button', { name: 'Xác nhận chuyển ca', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Chuyển ca nháp' })).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(page.locator('.schedule-cell').filter({ hasText: 'Lan' })).toHaveCount(1)
})

test('publish error opens the exact slot popup without navigating away', async ({ page }) => {
  await page.goto('/tests/schedule-ui/index.html')
  await page.evaluate(() => { (window as any).__failScheduleValidation = true })
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await page.getByRole('region', { name: 'Chi tiết lỗi công bố' }).getByRole('button').click()
  await expect(page.getByRole('dialog', { name: 'Chỉnh ô lịch' })).toBeVisible()
  await expect(page.locator('.schedule-assigned-row').filter({ hasText: 'Lan' })).toBeVisible()
  await expect(page).toHaveURL(/tests\/schedule-ui\/index.html$/)
})

test('clicking a locked learner opens one stable inspector without flashing the matrix', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/schedule-ui/index.html')

  const lockedCell = page.locator('.schedule-cell').filter({ hasText: 'Bình' })
  await expect(lockedCell.locator('svg[aria-label="Ca đã khóa"]')).toBeVisible()
  await expect(lockedCell.locator('button')).toHaveCount(0)
  await lockedCell.getByText('Bình', { exact: true }).click()

  await expect(page.getByRole('dialog', { name: 'Chỉnh ô lịch' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Mở khóa', exact: true })).toBeVisible()
  await expect(page.locator('.schedule-student-focus, .schedule-cell.is-student-highlight, .schedule-cell.is-availability-hover')).toHaveCount(0)
})
