import { test, expect } from '@playwright/test'
for (const width of [360, 390, 430]) {
  test(`production workspace manual confirm and continuation at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/tests/schedule-ui/index.html')
    await expect(page.getByRole('heading', { name: 'Xếp lịch PT' })).toBeVisible()
    await page.locator('.schedule-cell').filter({ hasText: 'Lan' }).focus()
    await page.keyboard.press('Enter')
    await page.getByRole('button', { name: 'Chọn Ngọc', exact: true }).click()
    const manualFooterLayout = await page.evaluate(() => {
      const inspector = document.querySelector('.schedule-inspector')?.getBoundingClientRect()
      const footer = document.querySelector('.schedule-manual-confirm')?.getBoundingClientRect()
      return inspector && footer ? { inspectorBottom: inspector.bottom, footerTop: footer.top, footerBottom: footer.bottom, viewportHeight: window.innerHeight } : null
    })
    expect(manualFooterLayout).not.toBeNull()
    expect(Math.abs(manualFooterLayout!.inspectorBottom - manualFooterLayout!.footerBottom)).toBeLessThanOrEqual(1)
    expect(manualFooterLayout!.footerTop).toBeGreaterThan(manualFooterLayout!.viewportHeight * .7)
    expect(await page.evaluate(() => (window as any).__scheduleCalls.filter((x: any) => x.operation === 'command').length)).toBe(0)
    await page.getByRole('button', { name: 'Xác nhận xếp ca', exact: true }).click()
    await expect(page.locator('.schedule-assigned-row').filter({ hasText: 'Ngọc' })).toBeVisible()
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Tối ưu tiếp', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Chọn chi nhánh' })).toBeDisabled()
    await expect(page.getByRole('combobox', { name: 'Chọn chi nhánh' })).toBeEnabled()
    const modes = await page.evaluate(() => (window as any).__scheduleCalls.filter((x: any) => x.operation === 'generate').map((x: any) => x.input.mode))
    expect(modes).toEqual(['continue'])
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  })
}
test('failed move leaves inspector and original session intact; retry succeeds', async ({ page }) => {
  await page.goto('/tests/schedule-ui/index.html')
  await page.locator('.schedule-cell').filter({ hasText: 'Lan' }).focus()
    await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Chuyển ca của Lan', exact: true }).click()
  await page.getByRole('combobox', { name: 'Ca đích', exact: true }).selectOption('T3-6')
  await page.evaluate(() => { (window as any).__failScheduleCommand = true })
  await page.getByRole('button', { name: 'Xác nhận chuyển ca', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('ca cũ được giữ')
  await expect(page.locator('.schedule-assigned-row').filter({ hasText: 'Lan' })).toBeVisible()
  await page.evaluate(() => { (window as any).__failScheduleCommand = false })
  await page.getByRole('button', { name: 'Xác nhận chuyển ca', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Chuyển ca nháp' })).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(page.locator('.schedule-cell').filter({ hasText: 'Lan' })).toHaveCount(1)
})

test('publish error opens the exact slot popup without navigating away', async ({ page }) => {
  await page.goto('/tests/schedule-ui/index.html')
  await page.evaluate(() => { (window as any).__failScheduleValidation = true })
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await page.getByRole('region', { name: 'Chi tiết lỗi công bố' }).getByRole('button').click()
  await expect(page.getByRole('dialog', { name: 'Chỉnh ô lịch' })).toBeVisible()
  await expect(page.locator('.schedule-assigned-row').filter({ hasText: 'Lan' })).toBeVisible()
  await expect(page).toHaveURL(/tests\/schedule-ui\/index.html$/)
})

test('learner name controls reveal availability and scheduled sessions without opening inspector', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/schedule-ui/index.html')

  const lockedCell = page.locator('.schedule-cell').filter({ hasText: 'Bình' })
  await expect(lockedCell.locator('svg[aria-label="Ca đã khóa"]')).toBeVisible()
  const studentName = lockedCell.locator('.schedule-cell__student')
  await expect(studentName).toHaveAttribute('aria-pressed', 'false')
  await studentName.focus()
  await expect(page.locator('.schedule-student-focus')).toContainText('Bình')
  await expect(page.locator('.schedule-cell.is-availability-hover')).toHaveCount(3)

  await studentName.click()
  await expect(page.locator('.schedule-student-focus')).toContainText('Bình')
  await expect(studentName).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.schedule-cell.is-student-highlight')).toHaveCount(1)
  await expect(page.getByRole('dialog', { name: 'Chỉnh ô lịch' })).toBeHidden()
})

test('manager opportunity pool shows strict tiers and filters against learner availability on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/schedule-ui/index.html')
  await page.getByRole('tab', { name: /Kho ca/ }).click()
  await expect(page.getByRole('heading', { name: 'Điều phối ca trống' })).toBeVisible()
  const opportunityMatrix = page.getByRole('region', { name: 'Ma trận tải ca còn trống' })
  await expect(opportunityMatrix).toBeVisible()
  expect(await opportunityMatrix.locator('button.is-priority-1').count()).toBeGreaterThan(0)
  expect(await opportunityMatrix.locator('button.is-priority-2').count()).toBeGreaterThan(0)
  expect(await opportunityMatrix.locator('button.is-priority-3').count()).toBeGreaterThan(0)
  await expect(page.getByText('Ưu tiên 1 · Ghép vào ca 1/2')).toBeVisible()
  await expect(page.getByText('Ưu tiên 3 · Các PT cùng chi nhánh còn lại')).toBeVisible()
  const officialPtSlots = page.locator('.schedule-opportunities__group.is-tier-2')
  await expect(officialPtSlots).toContainText('Ưu tiên 2 · PT chính thức cùng chi nhánh dưới 8 ca')
  expect(await officialPtSlots.getByRole('button').count()).toBeGreaterThan(0)
  await expect(officialPtSlots.getByText(/Khớp PT chính\/phụ/).first()).toBeVisible()
  await expect(officialPtSlots.locator('button.is-assigned-match')).toHaveCount(0)
  await page.getByLabel('Học viên cần xếp / đổi').selectOption('a')
  await expect(page.getByText('Ưu tiên 2 · PT chính thức cùng chi nhánh dưới 8 ca')).toBeVisible()
  await expect(officialPtSlots.getByText(/Khớp PT chính/).first()).toBeVisible()
  await expect(officialPtSlots.getByText(/Khớp PT phụ/).first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})

test('warning center separates learner input from real PT capacity', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/schedule-ui/index.html')
  await page.getByRole('tab', { name: /Cảnh báo/ }).click()
  await expect(page.getByText('Do hợp đồng', { exact: true })).toBeVisible()
  await page.locator('.schedule-warning-summary')
    .getByRole('button', { name: /Do lịch khách/ })
    .click()
  const learnerWarning = page.locator('.schedule-warning-student').filter({ hasText: 'Ngọc' })
  await expect(learnerWarning).toContainText('Do lịch khách')
  await expect(learnerWarning).toContainText('Học viên đăng ký chưa đủ số ngày rảnh')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})
